### ISSUE TITLE
Song doubles it length on iOS with always request desktop mode

### ISSUE THREAD

**Issue by IronMaltese** [snuffyDev/Beatbump#55]
I know that this is because of the rewrite, but songs double their length on iOS and the rest is just silence then the next song autoplays

**Comment by snuffyDev** [comment]
Weird. I’ve been looking at this since you’ve submitted but I haven’t made any changes to the Player component. So I’m stumped. Gonna keep this at the top of my priority list, but ideally should be fixed ASAP

**Comment by snuffyDev** [comment]
Weird, it works for me. Maybe it’s a caching issue, I’ll add the config for SvelteKits version checking and see if that changes it

**Comment by IronMaltese** [comment]
The problem still persists on a private tab in 15.3.1 so it might be a problem with the safari settings if you're not able to reproduce it, I'm updating to 15.4.1 rn to see if anything changes, and I'll try it on another iPhone soon to see if I encounter the same problem

**Comment by IronMaltese** [comment]
This works on other iOS browsers except safari, but I noticed on the newest update for iOS, the experimental GPU setting for media and the other one aren't there

**Comment by IronMaltese** [comment]
I've reset my settings for experimental settings, but the issue still appears on Safari for me

**Comment by snuffyDev** [comment]
These are my settings for Safari, I’m wondering if there’s any difference in our settings? I just updated last night to the latest iOS and it still works for me oddly enough 

![F37A8971-FE17-4ADD-9A9E-F66C0DE6C503](https://user-images.githubusercontent.com/72365477/162524117-1f51d177-71b9-4d19-8f81-e3150c6ddee4.png)
![CF06F009-D949-4E48-8AD3-BA3D966FA673](https://user-images.githubusercontent.com/72365477/162524127-16d0c0c6-0bb5-4196-a8d9-86f811c357d3.png)
![145C8326-8279-48DD-963B-1402A0E1A612](https://user-images.githubusercontent.com/72365477/162524135-75938c11-2ece-4255-93c5-8a83f642d618.png)
![7FF9FF34-010A-45BE-911D-32F14C8D85E7](https://user-images.githubusercontent.com/72365477/162524143-c0d445b8-a9a9-4af8-8f2e-efb4c3c4d024.png)
![56A0C041-9FD1-49CA-A32F-1DA0A37AA38A](https://user-images.githubusercontent.com/72365477/162524153-381051ae-25d1-4026-8e35-46e2ea18c1ea.png)
![C97763FB-C341-4944-927A-18E644762DFA](https://user-images.githubusercontent.com/72365477/162524160-14e6d490-915d-4a55-9f48-aea485c1cd1f.png)
![30AF9770-9853-45AF-80A7-76DBCE39B475](https://user-images.githubusercontent.com/72365477/162524164-4b974d72-c84b-4a24-a10e-4772502d8fd7.png)
![D57E4CD2-B83F-4B29-9E95-8E6276ADF4F4](https://user-images.githubusercontent.com/72365477/162524169-fe67e041-84b5-45e1-9de5-366362f74192.png)
![26FC35A3-91A5-45A7-92D1-EB92CD2FA729](https://user-images.githubusercontent.com/72365477/162524176-ffe1e52b-85cf-4c7e-afe7-51e0bbbc2c13.png)
![7C22C26E-9D15-4B05-96CB-B0F4C5A04783](https://user-images.githubusercontent.com/72365477/162524180-f90ede2d-a5d7-4166-be12-d47266b4e22b.png)
![E395FFA4-606F-40AE-BDA7-266EC328D3AA](https://user-images.githubusercontent.com/72365477/162524186-8abdcc3d-b8a8-4250-b029-be91f95d2096.png)

**Comment by snuffyDev** [comment]
https://user-images.githubusercontent.com/72365477/162525029-3db39116-bb10-4b41-b740-ab4d8661db1d.MOV

Video I took earlier

**Comment by IronMaltese** [comment]
I have those same experimental settings, but are there any I need to change, since I made them all default, the problem hasn't gone away still, I'm remarkably confused rn 😐

**Comment by IronMaltese** [comment]
https://user-images.githubusercontent.com/89056889/162537039-e6ef64a0-3e9d-4c38-9254-85093b30cff5.MOV

**Comment by snuffyDev** [comment]
This is very confusing. You said it works in other browsers on iOS, apart from Safari, correct?

I’m wondering if Apple changed anything to enable “features” for newer iPhones. I’ll keep digging into it, looking at your settings they seem to match mine. In the absolute worst case scenario and something completely broke from an Apple/YouTube update — I may have something in my back pocket but I’m unsure of if it will work. I’ll keep experimenting with it just in case.

**Comment by snuffyDev** [comment]
The core problem stems from DASH being incompatible with QuickTime which is what’s used on iOS. But recently I have been experimenting with using the iOS client request body to get iOS specific streams. 

Mainly I was trying to figure out a way to use the HLS streams that are available for actual streaming of the content, but that’s something that’s not so easy to do with the restrictions I’m working with. I didn’t try out the regular audio links though. So I’ll test that out in a little to see if it does anything different or not

**Comment by IronMaltese** [comment]
https://user-images.githubusercontent.com/89056889/162574870-bbfa78d4-2db4-460e-8efe-e5e4b97e5762.MOV This probably won't help, but here's the problem exactly

**Comment by IronMaltese** [comment]
Wassup, I hate that I didn't check this, but this bug resulted from requesting the desktop website for all websites, so even when the mobile app was requested, since it was already in desktop mode once, this bug kept occurring, sorry for any confusion or wasted time, this is really my fault but I hope the rewrite is worth it if that's still planned :)

**Comment by IronMaltese** [comment]
Background autoplay still doesn't work with the new settings though :/

**Comment by IronMaltese** [comment]
Idk if you wanna fix this behavior, so I’ll just leave it open and you can decide whether to close it or not

**Comment by Smig0l** [comment]
> I know that this is because of the rewrite, but songs double their length on iOS and the rest is just silence then the next song autoplays

it seems fixed in the master branch but not in the rewrite one


> Wassup, I hate that I didn't check this, but this bug resulted from requesting the desktop website for all websites, so even when the mobile app was requested, since it was already in desktop mode once, this bug kept occurring, sorry for any confusion or wasted time, this is really my fault but I hope the rewrite is worth it if that's still planned :)

songs double their lenght both in mobile and desktop version (i am on IOS 15.5)

**Comment by snuffyDev** [comment]
Experimenting with a potential fix 

https://user-images.githubusercontent.com/72365477/181095130-b9ae4c17-4b03-4420-8b42-9417868f1aa3.MOV

**Comment by snuffyDev** [comment]
Try this preview site: https://beatbump-hls.beatbump.workers.dev/trending

**Comment by Smig0l** [comment]
Yep works!

**Comment by IronMaltese** [comment]
HlS should be made default on iOS devices now, but I'll close this issue
